apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy-homolog
  labels:
    app: front-deploy-homolog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-deploy-homolog
  template:
    metadata:
      labels:
        app: front-deploy-homolog
    spec:
      containers:
      - name: front-deploy-homolog
        image: artearenahub/space-frontend-homolog:latest
        ports:
        - containerPort: 3000
