apiVersion: v1
kind: Service
metadata:
  name: front-svc-homolog
spec:
  selector:
    app: front-deploy-homolog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  