apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy-homolog
  labels:
    app: back-deploy-homolog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-deploy-homolog
  template:
    metadata:
      labels:
        app: back-deploy-homolog
    spec:
      initContainers:
      - name: back-homolog-init-container
        image: artearenahub/space-backend:latest
        envFrom:
        - secretRef:
            name: back-homolog-secret
      containers:
      - name: back-deploy-homolog
        image: artearenahub/space-backend:latest
        ports:
        - containerPort: 9000
        command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=9000"]

