apiVersion: v1
kind: Secret
metadata:
  name: back-homolog-secret
type: Opaque
data:
  SPACE_DB_HOST: 
  SPACE_DB_PORT: 3306
  SPACE_DB_DATABASE: xxx
  SPACE_DB_USERNAME: xxx
  SPACE_DB_PASSWORD: xxx


