apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-prod-ing
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-production"
    spec.ingressClassName: "public"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: alb
spec:
  ingressClassName: "public"
  tls:
  - hosts:
    - www.spacearena.net
    secretName: front-prod-cert
  rules:
  - host: www.spacearena.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: front-prod-svc
            port:
              number: 80
