apiVersion: v1
kind: Service
metadata:
  name: front-prod-svc
  annotations:
    external-dns.alpha.kubernetes.io/hostname: www.spacearena.net
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: front-deploy
