apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
type: Opaque
data:
  database-user: testes
  database-password: teste
  database-name: teste
  database-host: teste
  database-port: teste
