apiVersion: v1
kind: Service
metadata:
  name: template-original-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: template-original-deploy
